// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lianhong2758/RosmBot-MUL/server/ob11/ent/chat"
	"github.com/lianhong2758/RosmBot-MUL/server/ob11/ent/predicate"
)

// ChatUpdate is the builder for updating Chat entities.
type ChatUpdate struct {
	config
	hooks    []Hook
	mutation *ChatMutation
}

// Where appends a list predicates to the ChatUpdate builder.
func (cu *ChatUpdate) Where(ps ...predicate.Chat) *ChatUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *ChatUpdate) SetUpdatedAt(t time.Time) *ChatUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetGroupID sets the "group_id" field.
func (cu *ChatUpdate) SetGroupID(i int64) *ChatUpdate {
	cu.mutation.ResetGroupID()
	cu.mutation.SetGroupID(i)
	return cu
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (cu *ChatUpdate) SetNillableGroupID(i *int64) *ChatUpdate {
	if i != nil {
		cu.SetGroupID(*i)
	}
	return cu
}

// AddGroupID adds i to the "group_id" field.
func (cu *ChatUpdate) AddGroupID(i int64) *ChatUpdate {
	cu.mutation.AddGroupID(i)
	return cu
}

// SetUserID sets the "user_id" field.
func (cu *ChatUpdate) SetUserID(i int64) *ChatUpdate {
	cu.mutation.ResetUserID()
	cu.mutation.SetUserID(i)
	return cu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (cu *ChatUpdate) SetNillableUserID(i *int64) *ChatUpdate {
	if i != nil {
		cu.SetUserID(*i)
	}
	return cu
}

// AddUserID adds i to the "user_id" field.
func (cu *ChatUpdate) AddUserID(i int64) *ChatUpdate {
	cu.mutation.AddUserID(i)
	return cu
}

// SetTime sets the "time" field.
func (cu *ChatUpdate) SetTime(i int64) *ChatUpdate {
	cu.mutation.ResetTime()
	cu.mutation.SetTime(i)
	return cu
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (cu *ChatUpdate) SetNillableTime(i *int64) *ChatUpdate {
	if i != nil {
		cu.SetTime(*i)
	}
	return cu
}

// AddTime adds i to the "time" field.
func (cu *ChatUpdate) AddTime(i int64) *ChatUpdate {
	cu.mutation.AddTime(i)
	return cu
}

// SetMessageType sets the "message_type" field.
func (cu *ChatUpdate) SetMessageType(s string) *ChatUpdate {
	cu.mutation.SetMessageType(s)
	return cu
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (cu *ChatUpdate) SetNillableMessageType(s *string) *ChatUpdate {
	if s != nil {
		cu.SetMessageType(*s)
	}
	return cu
}

// SetMessageContent sets the "message_content" field.
func (cu *ChatUpdate) SetMessageContent(s string) *ChatUpdate {
	cu.mutation.SetMessageContent(s)
	return cu
}

// SetNillableMessageContent sets the "message_content" field if the given value is not nil.
func (cu *ChatUpdate) SetNillableMessageContent(s *string) *ChatUpdate {
	if s != nil {
		cu.SetMessageContent(*s)
	}
	return cu
}

// Mutation returns the ChatMutation object of the builder.
func (cu *ChatUpdate) Mutation() *ChatMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChatUpdate) Save(ctx context.Context) (int, error) {
	cu.defaults()
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChatUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChatUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChatUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *ChatUpdate) defaults() {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		v := chat.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
}

func (cu *ChatUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(chat.Table, chat.Columns, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt64))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(chat.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.GroupID(); ok {
		_spec.SetField(chat.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.AddedGroupID(); ok {
		_spec.AddField(chat.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.UserID(); ok {
		_spec.SetField(chat.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.AddedUserID(); ok {
		_spec.AddField(chat.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.Time(); ok {
		_spec.SetField(chat.FieldTime, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.AddedTime(); ok {
		_spec.AddField(chat.FieldTime, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.MessageType(); ok {
		_spec.SetField(chat.FieldMessageType, field.TypeString, value)
	}
	if value, ok := cu.mutation.MessageContent(); ok {
		_spec.SetField(chat.FieldMessageContent, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ChatUpdateOne is the builder for updating a single Chat entity.
type ChatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *ChatUpdateOne) SetUpdatedAt(t time.Time) *ChatUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetGroupID sets the "group_id" field.
func (cuo *ChatUpdateOne) SetGroupID(i int64) *ChatUpdateOne {
	cuo.mutation.ResetGroupID()
	cuo.mutation.SetGroupID(i)
	return cuo
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableGroupID(i *int64) *ChatUpdateOne {
	if i != nil {
		cuo.SetGroupID(*i)
	}
	return cuo
}

// AddGroupID adds i to the "group_id" field.
func (cuo *ChatUpdateOne) AddGroupID(i int64) *ChatUpdateOne {
	cuo.mutation.AddGroupID(i)
	return cuo
}

// SetUserID sets the "user_id" field.
func (cuo *ChatUpdateOne) SetUserID(i int64) *ChatUpdateOne {
	cuo.mutation.ResetUserID()
	cuo.mutation.SetUserID(i)
	return cuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableUserID(i *int64) *ChatUpdateOne {
	if i != nil {
		cuo.SetUserID(*i)
	}
	return cuo
}

// AddUserID adds i to the "user_id" field.
func (cuo *ChatUpdateOne) AddUserID(i int64) *ChatUpdateOne {
	cuo.mutation.AddUserID(i)
	return cuo
}

// SetTime sets the "time" field.
func (cuo *ChatUpdateOne) SetTime(i int64) *ChatUpdateOne {
	cuo.mutation.ResetTime()
	cuo.mutation.SetTime(i)
	return cuo
}

// SetNillableTime sets the "time" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableTime(i *int64) *ChatUpdateOne {
	if i != nil {
		cuo.SetTime(*i)
	}
	return cuo
}

// AddTime adds i to the "time" field.
func (cuo *ChatUpdateOne) AddTime(i int64) *ChatUpdateOne {
	cuo.mutation.AddTime(i)
	return cuo
}

// SetMessageType sets the "message_type" field.
func (cuo *ChatUpdateOne) SetMessageType(s string) *ChatUpdateOne {
	cuo.mutation.SetMessageType(s)
	return cuo
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableMessageType(s *string) *ChatUpdateOne {
	if s != nil {
		cuo.SetMessageType(*s)
	}
	return cuo
}

// SetMessageContent sets the "message_content" field.
func (cuo *ChatUpdateOne) SetMessageContent(s string) *ChatUpdateOne {
	cuo.mutation.SetMessageContent(s)
	return cuo
}

// SetNillableMessageContent sets the "message_content" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableMessageContent(s *string) *ChatUpdateOne {
	if s != nil {
		cuo.SetMessageContent(*s)
	}
	return cuo
}

// Mutation returns the ChatMutation object of the builder.
func (cuo *ChatUpdateOne) Mutation() *ChatMutation {
	return cuo.mutation
}

// Where appends a list predicates to the ChatUpdate builder.
func (cuo *ChatUpdateOne) Where(ps ...predicate.Chat) *ChatUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChatUpdateOne) Select(field string, fields ...string) *ChatUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Chat entity.
func (cuo *ChatUpdateOne) Save(ctx context.Context) (*Chat, error) {
	cuo.defaults()
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChatUpdateOne) SaveX(ctx context.Context) *Chat {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChatUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChatUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *ChatUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		v := chat.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
}

func (cuo *ChatUpdateOne) sqlSave(ctx context.Context) (_node *Chat, err error) {
	_spec := sqlgraph.NewUpdateSpec(chat.Table, chat.Columns, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeInt64))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chat.FieldID)
		for _, f := range fields {
			if !chat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(chat.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.GroupID(); ok {
		_spec.SetField(chat.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.AddedGroupID(); ok {
		_spec.AddField(chat.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.UserID(); ok {
		_spec.SetField(chat.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.AddedUserID(); ok {
		_spec.AddField(chat.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.Time(); ok {
		_spec.SetField(chat.FieldTime, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.AddedTime(); ok {
		_spec.AddField(chat.FieldTime, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.MessageType(); ok {
		_spec.SetField(chat.FieldMessageType, field.TypeString, value)
	}
	if value, ok := cuo.mutation.MessageContent(); ok {
		_spec.SetField(chat.FieldMessageContent, field.TypeString, value)
	}
	_node = &Chat{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
