// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/lianhong2758/RosmBot-MUL/server/ob11/ent/chat"
	"github.com/lianhong2758/RosmBot-MUL/server/ob11/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chatMixin := schema.Chat{}.Mixin()
	chatMixinFields0 := chatMixin[0].Fields()
	_ = chatMixinFields0
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescCreatedAt is the schema descriptor for created_at field.
	chatDescCreatedAt := chatMixinFields0[0].Descriptor()
	// chat.DefaultCreatedAt holds the default value on creation for the created_at field.
	chat.DefaultCreatedAt = chatDescCreatedAt.Default.(func() time.Time)
	// chatDescUpdatedAt is the schema descriptor for updated_at field.
	chatDescUpdatedAt := chatMixinFields0[1].Descriptor()
	// chat.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	chat.DefaultUpdatedAt = chatDescUpdatedAt.Default.(func() time.Time)
	// chat.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	chat.UpdateDefaultUpdatedAt = chatDescUpdatedAt.UpdateDefault.(func() time.Time)
}
